### ISSUE TITLE
I cannot send, receive or update peer information using cl-rest when clboss plugin is active.

### ISSUE THREAD

**Issue by JaviLib** [ZmnSCPxj/clboss#76]
Whenever I enable this plugin, I stop being able to send or receiving any LN payment through cl-rest, and also in spark-wallet. In addition, in RTL and Zeus I am unable to see the list of peers and channels connected.

In the moment I disable the plugin, everything works again.

This is the error in RTL logs:

```
rtlcln_build    | 2021-10-28T16:11:38.838854027Z [2021-10-28T16:11:38.838Z] ERROR: Peers => Peers List Error: {"name":"RequestError","message":"Error: socket hang up","cause":{"code":"ECONNRESET"},"error":{"code":"ECONNRESET"},"options":{"url":"https://lightningd:3002/v1/peer/listPeers","rejectUnauthorized":false,"json":true,"headers":{},"method":"GET","qs":{},"simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false}}
```

As a side note, just in case it is related, `topology` plugin is using 100% cpu of one of my cores since yesterday.

Version I am using: master, I think 11B or close.

**Comment by JaviLib** [comment]
I found the problem, it was due to be using an old version of clightning, the one in the docker image tagged as latest in fact was 0.9.3. With 10.1 it works ok. Closing.

**Comment by ZmnSCPxj** [comment]
CLBOSS takes up some amount of work on topology due to looking for  channel counterparties.  However once it has a set of candidates it will stop hogging the CPU.  It may not be version related after all, but due to this initial spike of searching.
